objects
js-tasks-ru/jsbasic-20210921-5_annakarpycheva pull request #3
Opened 2021-09-30 17:40 UTC by demogreat

2021-09-30 17:41 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-10-01 02:52 UTC, koalex requested changes
Нужно удалить `alert`-ы в **6-2**

2021-10-01 02:52 UTC, koalex commented on 2-module/2-task/index.js
> +alert( isEmpty(schedule) ); // true
`alert`-ы нужно удалить, они будут мешать тестам

2021-10-04 07:16 UTC, demogreat commented on 2-module/2-task/index.js
> +alert( isEmpty(schedule) ); // true
удалила

2021-10-04 07:16 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-10-04 12:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-10-05 04:42 UTC, koalex approved these changes

2021-10-05 04:42 UTC, merged